# Generated by Django 4.2.7 on 2023-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('done', 'Concluido'), ('in progress', 'Em progresso'), ('idle', 'Aguardando')], default='idle', max_length=20),
        ),
    ]
